access_token:
  url: https://api.oregonstate.edu/oauth2/token
  payload:
    client_id: client_id
    client_secret: client_secret
apiUrls:
  beaver_bus: https://api.oregonstate.edu/v1/beaverbus/routes
  terms: https://api.oregonstate.edu/v1/terms
  textbooks: https://api.oregonstate.edu/v1/textbooks
  routes: https://api.oregonstate.edu/v1/beaverbus/routes
  arrivals: https://api.oregonstate.edu/v1/beaverbus/arrivals
  vehicles: https://api.oregonstate.edu/v1/beaverbus/vehicles
