access_token:
  url: https://api.oregonstate.edu/oauth2/token
  payload:
    client_id: client_id
    client_secret: client_secret
  headers:
    content_type: application/x-www-form-urlencoded;charset=utf-8
api_options:
  - Quit
  - Beavers Bus
  - Terms
  - Search Text Books of a Term by a custom/any Date
  - Get Details of a Vehicle and its Stops given a specified Route, with ETA and current destination
general_strings:
  which_api: Which API data do you want to check?
  enter_choice: 'Enter your choice (0 or 1 or 2 or 3 or 4): '
  exiting: Exiting...
  invalid_choice: Invalid choice. Please try again.
apiUrls:
  beaver_bus: https://api.oregonstate.edu/v1/beaverbus/routes
  terms: https://api.oregonstate.edu/v1/terms
  textbooks: https://api.oregonstate.edu/v1/textbooks
  routes: https://api.oregonstate.edu/v1/beaverbus/routes
  arrivals: https://api.oregonstate.edu/v1/beaverbus/arrivals
  vehicles: https://api.oregonstate.edu/v1/beaverbus/vehicles
